<template>
  <div class="report-container">
    <!-- 1. 背景粒子 (使用 v-for 生成) -->
    <div class="particles">
      <div
        v-for="(p, i) in particles"
        :key="i"
        class="particle"
        :style="p.style"
      ></div>
    </div>

    <!-- 2. 背景音乐控制 -->
    <audio ref="audioRef" loop>
      <source
        src="https://music.163.com/song/media/outer/url?id=139774.mp3"
        type="audio/mpeg"
      />
    </audio>
    <div
      class="music-btn"
      :class="{ playing: isMusicPlaying }"
      @click="toggleMusic"
      v-show="isStarted"
    ></div>

    <!-- 3. 启动引导页 -->
    <transition name="fade">
      <div v-if="!isStarted" class="start-overlay">
        <div class="title">2025 年度学业报告</div>
        <div class="subtitle">开启你的专属数据记忆</div>
        <button class="start-btn" @click="startJourney">点击开启</button>
      </div>
    </transition>

    <!-- 4. 主滑动容器 -->
    <div class="swiper-box" ref="swiperRef">
      <!-- Page 1: 封面 -->
      <section
        class="page"
        :class="{ active: activeIndex === 0 }"
        data-index="0"
      >
        <div class="anim-item d-1 avatar-box">🎓</div>
        <div class="anim-item d-2 intro-text">
          你好，<span class="bold">{{ reportData.student_name }}</span>
        </div>
        <div class="anim-item d-3">
          <h1 class="main-title">这是你的<br />年度学业账单</h1>
        </div>
        <div class="anim-item d-4 desc mt-20">
          <p>{{ reportData.school_name }}</p>
          <p>{{ reportData.academic_year_name }} {{ reportData.term_name }}</p>
        </div>
        <div class="anim-item d-5 hint-text">向上滑动查看详情</div>
        <div class="arrow-up"></div>
      </section>

      <!-- Page 2: 总览 -->
      <section
        class="page"
        :class="{ active: activeIndex === 1 }"
        data-index="1"
      >
        <div class="anim-item d-1 desc">这一学期</div>
        <div class="anim-item d-2 desc">你在知识的海洋里遨游</div>

        <div class="glass-card anim-item d-3 my-30">
          <div class="desc">平均绩点 (GPA) 达到</div>
          <div class="highlight-text">{{ reportData.average_gpa || "-" }}</div>
          <div class="desc mt-20">累计获得学分</div>
          <div class="highlight-text big-num">
            {{ reportData.total_credits || "-" }}
          </div>
        </div>

        <div class="anim-item d-4 desc">每一分的耕耘，<br />都算数。</div>
        <div class="arrow-up"></div>
      </section>

      <!-- Page 3: 成绩单 -->
      <section
        class="page"
        :class="{ active: activeIndex === 2 }"
        data-index="2"
      >
        <div class="anim-item d-1">
          <h1>成绩透视</h1>
          <p class="desc">你在这些课程中留下了足迹</p>
        </div>

        <div class="glass-card anim-item d-2 scroll-card">
          <div class="grade-scroll">
            <div v-if="reportData.grades.length === 0" class="empty-tip">
              暂无成绩
            </div>
            <div
              v-else
              v-for="(g, idx) in formattedGrades"
              :key="idx"
              class="grade-row"
            >
              <span class="subject-name">{{ g.subject_name }}</span>
              <span class="grade-val">{{ g.displayScore }}</span>
            </div>
          </div>
        </div>

        <div class="anim-item d-3 desc small-hint">
          * 仅展示已录入成绩的科目
        </div>
        <div class="arrow-up"></div>
      </section>

      <!-- Page 4: 雷达图 -->
      <section
        class="page"
        :class="{ active: activeIndex === 3 }"
        data-index="3"
      >
        <div class="anim-item d-1">
          <h1>多维能力</h1>
          <p class="desc">不被定义，全面发展</p>
        </div>

        <div class="glass-card anim-item d-2 chart-card">
          <div ref="chartRef" class="chart-container"></div>
        </div>

        <div class="anim-item d-3 desc mt-20">
          你的强项在于 <span class="gold-text">{{ strongAbility }}</span>
        </div>
        <div class="arrow-up"></div>
      </section>

      <!-- Page 5: 寄语 -->
      <section
        class="page"
        :class="{ active: activeIndex === 4 }"
        data-index="4"
      >
        <div class="anim-item d-1 w-full">
          <div class="desc">
            班主任 {{ reportData.header_teacher }} 写给你的话：
          </div>
          <div class="glass-card quote-card">
            <span class="quote-mark left">“</span>
            <div class="quote-text">{{ displayComment }}</div>
            <span class="quote-mark right">”</span>
          </div>
        </div>

        <div class="anim-item d-3 footer-section">
          <h1>2026</h1>
          <p class="desc">保持热爱，奔赴山海</p>
          <div class="footer-note">Generated by Vue Student Report</div>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted, nextTick } from "vue";
import { useRoute } from "vue-router";
import * as echarts from "echarts";

const route = useRoute();
const studentId = route.params.studentId;

// --- 1. 数据源 ---
const reportData = reactive({
  school_name: "上海师范大学附属虹口中学",
  semester_name: "1-22周",
  term_name: "第一学期",
  academic_year_name: "2025-2026学年",
  student_name: "蔡欣妍",
  header_teacher: "姚峻杰",
  total_credits: "50.0",
  average_gpa: "3.5",
  grades: [
    {
      subject_name: "英语",
      score: "0.0",
      usual_score: "50.0",
      grade_level: "E",
      midterm_score: null,
      finalterm_score: null,
    },
    {
      subject_name: "政治",
      score: null,
      midterm_score: "74.6",
      finalterm_score: "84.0",
      usual_score: "25.1",
      remarks: "sss",
    },
  ],
  moral_education_comment:
    "该生在校期间表现良好，积极参与集体活动，学习态度端正，希望能保持热情，继续努力。",
  abilities: {
    study_ability: 4,
    logical_thinking: 3,
    creativity: 2,
    teamwork: 3,
    responsibility: 3,
  },
});

// --- 2. 状态控制 ---
const isStarted = ref(false);
const isMusicPlaying = ref(false);
const activeIndex = ref(0);
const audioRef = ref(null);
const chartRef = ref(null);
const swiperRef = ref(null);

// --- 3. 计算属性 (数据逻辑) ---

// 格式化成绩列表
const formattedGrades = computed(() => {
  return reportData.grades.map((g) => {
    let displayScore = g.score;
    // 逻辑：如果分数为0或空，优先取期末分，其次取等级
    if (!displayScore || displayScore === "0.0") {
      if (g.finalterm_score) displayScore = g.finalterm_score;
      else if (g.grade_level) displayScore = g.grade_level;
      else displayScore = "-";
    }
    return { ...g, displayScore };
  });
});

// 计算最强能力
const strongAbility = computed(() => {
  const map = {
    study_ability: "学习能力",
    logical_thinking: "逻辑思维",
    creativity: "创造力",
    teamwork: "团队合作",
    responsibility: "责任感",
  };
  let maxVal = 0;
  let maxKey = "study_ability";
  for (const [key, val] of Object.entries(reportData.abilities)) {
    if (val > maxVal) {
      maxVal = val;
      maxKey = key;
    }
  }
  return map[maxKey];
});

// 格式化评语
const displayComment = computed(() => {
  return reportData.moral_education_comment === "1231"
    ? "暂无详细评语"
    : reportData.moral_education_comment;
});

// 生成粒子配置
const particles = ref([]);
const initParticles = () => {
  for (let i = 0; i < 20; i++) {
    const size = Math.random() * 20 + 5;
    particles.value.push({
      style: {
        width: `${size}px`,
        height: `${size}px`,
        left: `${Math.random() * 100}%`,
        animationDuration: `${Math.random() * 10 + 5}s`,
        animationDelay: `${Math.random() * 5}s`,
      },
    });
  }
};

// --- 4. 交互逻辑 ---

const startJourney = async () => {
  isStarted.value = true;
  if (audioRef.value) {
    try {
      await audioRef.value.play();
      isMusicPlaying.value = true;
    } catch (e) {
      console.warn("Autoplay blocked:", e);
    }
  }
  // 确保 DOM 渲染后初始化图表
  nextTick(() => {
    initChart();
  });
};

const toggleMusic = () => {
  if (!audioRef.value) return;
  if (isMusicPlaying.value) {
    audioRef.value.pause();
  } else {
    audioRef.value.play();
  }
  isMusicPlaying.value = !isMusicPlaying.value;
};

// --- 5. ECharts 初始化 ---
const initChart = () => {
  if (!chartRef.value) return;
  const myChart = echarts.init(chartRef.value);
  const ab = reportData.abilities;

  const option = {
    radar: {
      indicator: [
        { name: "学习", max: 5 },
        { name: "逻辑", max: 5 },
        { name: "创造", max: 5 },
        { name: "协作", max: 5 },
        { name: "责任", max: 5 },
      ],
      splitNumber: 4,
      axisName: { color: "#fbd786", fontSize: 14 },
      splitLine: { lineStyle: { color: "rgba(255,255,255,0.1)" } },
      splitArea: { show: false },
      axisLine: { lineStyle: { color: "rgba(255,255,255,0.1)" } },
    },
    series: [
      {
        type: "radar",
        data: [
          {
            value: [
              ab.study_ability,
              ab.logical_thinking,
              ab.creativity,
              ab.teamwork,
              ab.responsibility,
            ],
            name: "能力值",
            areaStyle: {
              color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                { offset: 0, color: "#f7797d" },
                { offset: 1, color: "#fbd786" },
              ]),
            },
            lineStyle: { width: 2, color: "#fbd786" },
            itemStyle: { color: "#fff" },
          },
        ],
      },
    ],
  };
  myChart.setOption(option);

  // 响应式大小
  window.addEventListener("resize", () => myChart.resize());
};

// --- 6. 滚动监听 (Intersection Observer) ---
onMounted(() => {
  initParticles();

  // 设置观察器监听每一页的可见性
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          // 获取 data-index 属性更新 activeIndex
          const index = Number(entry.target.dataset.index);
          activeIndex.value = index;
        }
      });
    },
    { threshold: 0.4 },
  ); // 40% 可见即触发

  // 观察所有 .page 元素
  const pages = document.querySelectorAll(".page");
  pages.forEach((page) => observer.observe(page));
});
</script>

<style scoped>
/* 样式变量 */
.report-container {
  --bg-deep: #0f0c29;
  --bg-mid: #302b63;
  --bg-light: #24243e;
  --accent-gold: #fbd786;
  --accent-pink: #f7797d;
  --text-main: #ffffff;
  --glass-bg: rgba(255, 255, 255, 0.1);
  --glass-border: rgba(255, 255, 255, 0.2);

  background: linear-gradient(
    to bottom,
    var(--bg-deep),
    var(--bg-mid),
    var(--bg-light)
  );
  font-family: "Helvetica Neue", "PingFang SC", sans-serif;
  color: var(--text-main);
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  position: relative;
}

/* 粒子背景 */
.particles {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  z-index: 0;
}
.particle {
  position: absolute;
  background: rgba(255, 255, 255, 0.3);
  border-radius: 50%;
  animation: floatUp infinite linear;
}
@keyframes floatUp {
  0% {
    transform: translateY(100vh) scale(0);
    opacity: 0;
  }
  50% {
    opacity: 0.8;
  }
  100% {
    transform: translateY(-10vh) scale(1.5);
    opacity: 0;
  }
}

/* 音乐按钮 */
.music-btn {
  position: fixed;
  top: 20px;
  right: 20px;
  width: 36px;
  height: 36px;
  z-index: 100;
  background: url("https://s1.ax1x.com/2023/01/01/pSjLZ4K.png") no-repeat
    center/contain;
  background-color: rgba(0, 0, 0, 0.3);
  border-radius: 50%;
  border: 2px solid rgba(255, 255, 255, 0.3);
  cursor: pointer;
}
.music-btn.playing {
  animation: rotate 4s linear infinite;
}
@keyframes rotate {
  100% {
    transform: rotate(360deg);
  }
}

/* 启动遮罩 */
.start-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: #000;
  z-index: 2000;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.fade-leave-active {
  transition: opacity 0.8s;
}
.fade-leave-to {
  opacity: 0;
}

.title {
  font-size: 24px;
  letter-spacing: 2px;
  margin-bottom: 10px;
}
.subtitle {
  font-size: 14px;
  color: #999;
  margin-bottom: 30px;
}
.start-btn {
  padding: 10px 40px;
  border: 1px solid #fff;
  background: transparent;
  color: #fff;
  border-radius: 30px;
  font-size: 16px;
  cursor: pointer;
  animation: pulse 2s infinite;
}

/* 滑动逻辑 */
.swiper-box {
  height: 100%;
  scroll-snap-type: y mandatory;
  overflow-y: scroll;
  scroll-behavior: smooth;
}
.swiper-box::-webkit-scrollbar {
  display: none;
}

.page {
  height: 100vh;
  width: 100vw;
  scroll-snap-align: start;
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 30px;
  box-sizing: border-box;
}

/* 动画进场系统 */
.anim-item {
  opacity: 0;
  transform: translateY(30px);
  transition: all 1s cubic-bezier(0.22, 1, 0.36, 1);
}
.page.active .anim-item {
  opacity: 1;
  transform: translateY(0);
}
.d-1 {
  transition-delay: 0.1s;
}
.d-2 {
  transition-delay: 0.3s;
}
.d-3 {
  transition-delay: 0.5s;
}
.d-4 {
  transition-delay: 0.7s;
}
.d-5 {
  transition-delay: 0.9s;
}

/* 文本与排版 */
h1 {
  font-size: 28px;
  font-weight: 300;
  margin-bottom: 10px;
}
.desc {
  font-size: 15px;
  color: #ddd;
  line-height: 1.6;
}
.highlight-text {
  font-size: 48px;
  font-weight: bold;
  background: linear-gradient(45deg, var(--accent-gold), var(--accent-pink));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  margin: 10px 0;
  font-family: "Impact", sans-serif;
}
.big-num {
  font-size: 60px;
}
.gold-text {
  color: var(--accent-gold);
  font-weight: bold;
}
.bold {
  font-weight: bold;
}
.mt-20 {
  margin-top: 20px;
}
.my-30 {
  margin: 30px 0;
}
.w-full {
  width: 100%;
}

/* 毛玻璃卡片 */
.glass-card {
  background: var(--glass-bg);
  backdrop-filter: blur(10px);
  border: 1px solid var(--glass-border);
  border-radius: 16px;
  padding: 20px;
  box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3);
  width: 100%;
}

/* 元素样式 */
.avatar-box {
  width: 100px;
  height: 100px;
  border-radius: 50%;
  border: 2px solid rgba(255, 255, 255, 0.8);
  margin: 0 auto 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 40px;
  background: rgba(255, 255, 255, 0.2);
}

.grade-scroll {
  max-height: 45vh;
  overflow-y: auto;
}
.grade-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}
.grade-val {
  font-size: 18px;
  color: var(--accent-gold);
  font-weight: bold;
}

.chart-container {
  width: 100%;
  height: 300px;
}

.quote-card {
  position: relative;
  margin-top: 20px;
}
.quote-text {
  padding: 10px;
  font-style: italic;
  line-height: 1.8;
  text-align: justify;
}
.quote-mark {
  position: absolute;
  font-size: 40px;
  opacity: 0.3;
}
.quote-mark.left {
  top: -10px;
  left: 10px;
}
.quote-mark.right {
  bottom: -20px;
  right: 10px;
}

.footer-section {
  margin-top: 50px;
  text-align: center;
}
.footer-note {
  margin-top: 30px;
  font-size: 12px;
  color: #666;
}

/* 底部指示箭头 */
.arrow-up {
  position: absolute;
  bottom: 30px;
  left: 50%;
  transform: translateX(-50%) rotate(45deg);
  width: 24px;
  height: 24px;
  border-top: 2px solid rgba(255, 255, 255, 0.5);
  border-left: 2px solid rgba(255, 255, 255, 0.5);
  animation: arrowAnim 2s infinite;
  opacity: 0;
  transition: opacity 1s;
}
.page.active .arrow-up {
  opacity: 1;
  transition-delay: 1.5s;
}

@keyframes arrowAnim {
  0% {
    transform: translateX(-50%) rotate(45deg) translate(0, 0);
    opacity: 0;
  }
  50% {
    opacity: 1;
  }
  100% {
    transform: translateX(-50%) rotate(45deg) translate(-10px, -10px);
    opacity: 0;
  }
}

@keyframes pulse {
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.05);
  }
  100% {
    transform: scale(1);
  }
}
</style>
